services:

  config:
    image: mongo:8
    container_name: config
    hostname: config
    command: >
      mongod --configsvr --replSet cfg --port 27019 --bind_ip_all

  shard1:
    image: mongo:8
    container_name: shard1
    hostname: shard1
    command: >
      mongod --shardsvr --port 27018 --bind_ip_all

  shard2:
    image: mongo:8
    container_name: shard2
    hostname: shard2
    command: >
      mongod --shardsvr --port 27018 --bind_ip_all

  mongos:
    image: mongo:8
    container_name: mongos
    hostname: mongos
    depends_on:
      - config
    command: >
      mongos --configdb cfg/config:27019 --bind_ip_all
    ports:
      - "27017:27017"